language: julia

os:
    - linux
    - osx
    - windows

julia:
    - 1.0
    - 1.2
    - nightly

matrix:
  fast_finish: true
  allow_failures:
  - julia: nightly

notifications:
    email: false

codecov: true

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --color=yes --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --color=yes --project=docs docs/make.jl
      after_success: skip
